### ISSUE TITLE
Missing google services file

### ISSUE THREAD

**Issue by crjacinro** [lmj0011/jetpack-release-tracker#5]
Hi. 

Tried to fork and clone your repo and after building it clean, I got this error

File google-services.json is missing. The Google Services Plugin cannot function without it. 

Thanks for the help

**Comment by lmj0011** [comment]
`google-services.json` has oauth credentials in it that I don't want exposed. I recommend you create your own `google-services.json` see https://firebase.google.com/docs/android/setup#console


As a quick workaround, you should be able to comment these 2 lines out in [app/build.gradle](https://github.com/lmj0011/jetpack-release-tracker/blob/master/app/build.gradle), and still build the app since the Google Services plugin is only being used by Crashlytics

```gradle
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'
```

**Comment by crjacinro** [comment]
Thanks. Able to build now.
